### DISCUSSION TITLE
Openshift/Okd support?

### DISCUSSION THREAD

**Discussion by leonidas-o** [gotenberg/gotenberg#1042] [Q&A] [answered]
I see a permission denied error in my open shift/okd cluster:
```
{"level":"error","ts":1731426508.9073021,"logger":"api","msg":"convert HTML to PDF: convert to PDF: process first start: start process: run exec allocator: chrome failed to start:\nmkdir: cannot create directory '//.local': Permission denied\ntouch: cannot touch '//.local/share/applications/mimeapps.list': No such file or directory\nchrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information.\n","trace":"f031abb3-c554-41ca-ba8c-745b65b73ba2","remote_ip":"x.x.x.x","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"","status":500,"latency":794288676,"latency_human":"794.288676ms","bytes_in":167432,"bytes_out":21}
```

In the past I had already issues with other images, especially when I see something like: https://gotenberg.dev/docs/getting-started/installation#kubernetes
where it says, I should use `runAsUser: 1001`, which you actually don't do in OpenShift.

This could be resolved with the following in the Dockerfile.
"OpenShift: Support arbitrary user ids"
https://docs.openshift.com/container-platform/4.15/openshift_images/create-images.html#use-uid_create-images
```
RUN chgrp -R 0 /home/gotenberg && \
    chmod -R g=u /home/gotenberg
```

Any one here, who could bring up Gotenberg in a restricted cluster like OpenShift/Okd (maybe without creating a custom Gutenberg image)?

**Comment by gulien** [comment]
Hey @leonidas-o 👋 

I could create a custom variant for OpenShift (like [CloudRun](https://github.com/gotenberg/gotenberg/blob/main/build/Dockerfile.cloudrun)), e.g., `gotenberg:8-openshift`.  In the meantime, could you build the following image and check if it works as expected?

```Dockerfile
FROM gotenberg/gotenberg:8

USER root

RUN chgrp -R 0 /home/gotenberg && \
    chmod -R g=u /home/gotenberg

USER gotenberg
```

**Reply by leonidas-o** [reply]
@gulien thanks for the quick response. Yes, that sounds good. Sure thing, will test that and report back.

**Reply by leonidas-o** [reply]
The pod is not comming up, the logs show:
`exec /usr/bin/tini: exec format error `

**Reply by gulien** [reply]
Did you build it on another architecture (for instance, arm64) than the one on OpenShift?

**Reply by leonidas-o** [reply]
ahhh of course, sorry for that. I've built it now on a linux machine but I get the same error as above:
```
{"level":"error","ts":1731596536.994974,"logger":"api","msg":"convert HTML to PDF: convert to PDF: process first start: start process: run exec allocator: chrome failed to start:\nmkdir: cannot create directory '//.local': Permission denied\ntouch: cannot touch '//.local/share/applications/mimeapps.list': No such file or directory\nchrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information.\n","trace":"3a190753-...","remote_ip":"x.x.x.x","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"","status":500,"latency":809039605,"latency_human":"809.039605ms","bytes_in":50832,"bytes_out":21}
```


I then tried the following Dockerfile, as I have an image running where I'm using USER 1001:
```Dockerfile
FROM gotenberg/gotenberg:8

USER root

RUN chgrp -R 0 /home/gotenberg && \
    chmod -R g=u /home/gotenberg && \
    chown 1001:0 /home/gotenberg

USER 1001
```

**Reply by gulien** [reply]
Did it work with the USER 1001? 😄

**Reply by leonidas-o** [reply]
oh sorry, somehow I missed to write down the last sentence. No it didn't work with that either. So with USER 1001 I'm getting the same error:
```
{"level":"error","ts":1731596536.994974,"logger":"api","msg":"convert HTML to PDF: convert to PDF: process first start: start process: run exec allocator: chrome failed to start:\nmkdir: cannot create directory '//.local': Permission denied\ntouch: cannot touch '//.local/share/applications/mimeapps.list': No such file or directory\nchrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information.\n","trace":"3a190753-...","remote_ip":"x.x.x.x","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"","status":500,"latency":809039605,"latency_human":"809.039605ms","bytes_in":50832,"bytes_out":21}
```


I wonder where that path `.local/share/...` should be: `mkdir: cannot create directory '//.local': Permission denied\ntouch: cannot touch '//.local/share/applications/mimeapps.list'`. 
Inside `/home/gotenberg`?
I can enter the container and I can `mkdir .local` without any issues.

Executing `id` inside the container gives me:
```
uid=1000710000(1000710000) gid=0(root) groups=0(root),1000710000
```

 Any ideas?

**Reply by gulien** [reply]
Looks like Chromium does not have the permission to create a mandatory file. Is the filesystem immutable in OpenShift?

**Reply by leonidas-o** [reply]
No, Openshift uses by default `restricted-v2` scc (https://docs.openshift.com/container-platform/4.15/authentication/managing-security-context-constraints.html#default-sccs_configuring-internal-oauth). I also checked the pod, it is using `restricted-v2`. The note in the docs for that specific scc says: 
```
The restricted-v2 SCC is the most restrictive of the SCCs that is included by default with the system. However, you can create a custom SCC that is even more restrictive. For example, you can create an SCC that restricts readOnlyRootFilesystem to true.
```
So for me, the docs clearly state that it is the most restrictive but `readOnlyRootFilesystem` is not set here. And I entered the container and was able to create files without any issue (`touch /var/tmp/test`,  `touch ~/test`). 

Could selinux block here? Or maybe changing the linux file ownership where chromium wants to write?

**Reply by leonidas-o** [reply]
@gulien I added the following line to `RUN` inside the Dockerfile: `mkdir /.local && chmod 777 /.local`
and the error now looks a bit different/ shorter: 
```
{"level":"error","ts":1731853976.3793793,"logger":"api","msg":"convert HTML to PDF: convert to PDF: process first start: start process: run exec allocator: chrome failed to start:\nchrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information.\n","trace":"dedd4b79-4324-4569-85a9-5710302426c0","remote_ip":"x.x.x.x","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"","status":500,"latency":887469450,"latency_human":"887.46945ms","bytes_in":50832,"bytes_out":21}
```
Why `--database is required`?

**Reply by gulien** [reply]
Your issue looks the same as https://github.com/gotenberg/gotenberg/issues/949. Chromium struggles to start because of some permission issue.

**Reply by leonidas-o** [reply]
Hmm, looks like the solution for him: `I tried setting readOnlyRootFilesystem: false now, and the pod starts successfully:`.
My pod is starting successfully however. Nevertheless, I added the following to the deployment, but I still get the same error (`--database is required`) as above.

```yaml
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
        - name: tmp
          emptyDir: {}
```

**Comment by leonidas-o** [comment, marked as answer]
@gulien okay got it working now.
So far I'm using the following setup

The key to make it work was however to set the two `XDG_CONFIG_HOME`, `XDG_CACHE_HOME` env vars in the deployment file. Don't know if the volume and volumeMount contributes to the success, but this is what currently works on OpenShift/ OKD with `restricted-v2` scc. So what are the next steps, do you see any optimisations? Will you provide a custom variant like `gotenberg:8-openshift`?

I also wonder why the dir `/.local` is in root and does it have to be there? Does it make sense to move it somewhere else (e.g. like into `/home/gotenberg` if possible?

Your suggested Dockerfile slightly modified.
```Dockerfile
FROM gotenberg/gotenberg:8

USER root

RUN chgrp -R 0 /home/gotenberg && \
    chmod -R g=u /home/gotenberg && \
    chown 1001:0 /home/gotenberg && \
    mkdir /.local && chown 1001:0 /.local

USER 1001
```
Gotenberg deployment file:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  namespace: my-namespace
  labels:
    app.kubernetes.io/name: gotenberg
    app.kubernetes.io/instance: gotenberg
    app.kubernetes.io/managed-by: agocd
    app: gotenberg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        ...
    spec:
      containers:
      - name: gotenberg
        image: my-registry.my-domain.com/gotenberg/gotenberg:8-openshift
        imagePullPolicy: Always
        env:
        - name: XDG_CONFIG_HOME
          value: "/tmp/.chromium"
        - name: XDG_CACHE_HOME
          value: "/tmp/.chromium"
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 250m
        ports:
        - name: tcp-3000
          containerPort: 3000
          protocol: TCP
        startupProbe:
          httpGet:
            path: /health
            port: tcp-3000
          failureThreshold: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: tcp-3000
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: tcp-3000
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
        - name: tmp
          emptyDir: {}
```

**Reply by gulien** [reply]
Hey @leonidas-o,

I don't think I'll create a custom variant for openshift, at least for now, as I cannot test it easily.

**Reply by leonidas-o** [reply]
@gulien too bad. How do you test it for cloud run?
You should maybe consider, that this Dockerfile/ configuration could be the new default for all. Also the changes are a recommendation from the RedHat OpenShift docs and not something made up just to make it work. If the Image made by this Dockerfile runs in such a strict environment like OpenShift with restricted-v2 scc, then it will run in any other k8s cluster with less strict security settings, right?
So that being said, would it make sense, to adapt the default Dockerfile with that few lines (+ adding `XDG_CONFIG_HOME`, `XDG_CACHE_HOME` env vars to your docs) and just test it, how you would test it anyway? So if all your tests pass with that conf, then you could have it as new default, no official OpenShift support, because you can't test it easily but unofficially this would simply work in OpenShift, too.
Does that make sense, or do you see any issues?

**Reply by gulien** [reply]
> If the Image made by this Dockerfile runs in such a strict environment like OpenShift with restricted-v2 scc, then it will run in any other k8s cluster with less strict security settings, right?

Indeed, good point! 👍 

Still, I wonder what would be the impact for existing users 🤔 Might require a new major release.

**Reply by leonidas-o** [reply]
Yes, definitely a major release, as we can't really predict what could happen, there are simply to many cluster possibilities, god knows in what env the community is running gotenberg (GCP, AWS, Azure, plain k8s, OpenShift etc.) But for sure, OpenShift is one of the most restricted out there (maybe it is even the most restricted, when thinking of the scc and SELinux active on each node etc. don't really know others except plain k8s, which is completely open by default).

So yes, maybe this could be a chance to bring "a bit" more security into gotenberg, at least from the image build perspective. I'm curious, if you adapt the original Dockerfile, incorporate that, test everything in your own stack, will everything just work? You can try that, if you find some time.

**Reply by gulien** [reply]
In my case I'm pretty sure it will work, but who knows for other folks 😄 

Converting this to an issue so that I can keep track of it! No ETA though 😉

**Reply by leonidas-o** [reply]
Yes sure, take your time. For now, I can create a gitlab pipeline to build the custom image for my cluster. Nevertheless I still hope an official decision won't take to long ;)

**Reply by peterfarrell** [reply]
I used the `Dockerfile` from this answer, built an image, and deployed to OpenShift. I enabled `debug` level logging and noticed the follow messages.

I was able to get this error to go away by mounting an empty volume for `/.local`:
```shell
{"level":"debug","ts":1734054920.7442284,"logger":"chromium.browser","msg":"start process"}
{"level":"debug","ts":1734054920.7535849,"logger":"chromium.browser","msg":"mkdir: cannot create directory '//.local/share': Permission denied\n"}
{"level":"debug","ts":1734054920.7551382,"logger":"chromium.browser","msg":"touch: cannot touch '//.local/share/applications/mimeapps.list': No such file or directory\n"}
```

I tried to fix this issue by creating the directory and setting various owners without success:
```shell
{"level":"debug","ts":1734054535.9590905,"logger":"chromium.browser","msg":"[18:37:1213/014855.862157:ERROR:nss_util.cc(49)] Failed to create /.pki/nssdb directory.\n"}
```

Not sure if seeing this many times in the log is normal operations or something to be concerned about?
```shell
{"level":"debug","ts":1734054537.860529,"logger":"chromium.browser","msg":"[18:52:1213/014857.860314:ERROR:zygote_host_impl_linux.cc(279)] Failed to adjust OOM score of renderer with pid 149: Permission denied (13)\n"}
```

Dockerfile and deployment used:

`Dockerfile`:
```dockerfile
```docker
FROM gotenberg/gotenberg:8

USER root

RUN chgrp -R 0 /home/gotenberg && \
    chmod -R g=u /home/gotenberg && \
    chown 1001:0 /home/gotenberg && \
    mkdir /.local && chown 1001:0 /.local

USER 1001
```

`deployment.yml `(scrubbed):
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
  name: gotenberg-8
  namespace: XXXXXXX
  labels:
    app: gotenberg-8
    app.kubernetes.io/component: gotenberg-8
    app.kubernetes.io/instance: gotenberg-8
    app.kubernetes.io/name: gotenberg-8
    app.kubernetes.io/part-of: gotenberg-8
    app.openshift.io/runtime-namespace: XXXXXX
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg-8
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gotenberg-8
        deployment: gotenberg-8
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.openshift.io/restartedAt: '2024-12-12T21:33:08.063Z'
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
        - name: local
          emptyDir: {}
      containers:
        - resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          name: gotenberg-8
          command:
            - gotenberg
          env:
            - name: XDG_CONFIG_HOME
              value: /tmp/.chromium
            - name: XDG_CACHE_HOME
              value: /tmp/.chromium
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - name: tcp-3000
              containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: local
              mountPath: /.local
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/XXXXXX/8-openshift@sha256:17df24078b80f9181c54b256e683cddac297295ee3e5991741864e5b648d7095
          args:
            - '--api-timeout'
            - 75s
            - '--log-level'
            - debug
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```
