### DISCUSSION TITLE
The "background-image" is being printed only on the first page (chromium)

### DISCUSSION THREAD

**Discussion by lzakrzewski** [gotenberg/gotenberg#386] [Q&A]
Hello :wave:

I'm trying to add a watermark to every single page of my PDF.
It seems that `goutenberg` can render background images (watermark) only on the first page, interestingly all the pages have background color applied.

I'm using `gotenberg` version 6.x but I also tried to upgrade to ver 7 and it didn't help,

The CSS:

```css
        body {
            font-family: sans-serif;
            background-image: url('watermark.png');
            background-color: lightblue;
        }
        
        section {
            page-break-inside: avoid;
        }
```

The printed documents (note 2nd, 3rd... pages don't have watermark):
![Screenshot from 2021-11-27 15-53-53](https://user-images.githubusercontent.com/4248462/143688308-0c0cdcd0-427c-400c-9456-7d61f9f6592d.png)
