### DISCUSSION TITLE
How to disable health check logging?

### DISCUSSION THREAD

**Discussion by thomastvedt** [gotenberg/gotenberg#443] [Q&A] [answered]
I'm deploying gutenberg to Kubernetes using a custom helm chart. I want to disable logging on the `/health` endpoint, this us currently logging a lot and costing me money in azure log.

I didn't find any documentation, but found `api-disable-health-check-logging` here:
https://github.com/gotenberg/gotenberg/blob/030b358b0e8b8a58c2e4d5fefcf049b71301d1d9/pkg/modules/api/api.go#L172

But I'm not successful in applying it yet.. I tried adding `--api-disable-health-check-logging` as argument, environment variable.. How can I use this flag?

From my helm chart templates:

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appname }}
spec:
  replicas: {{  .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname}}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: {{ .Values.appname}}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: "--api-disable-health-check-logging"
              value: "true"

```

**Comment by gulien** [comment]
Hello @thomastvedt,

The flags (a.k.a modules properties) are parts of the command, not environment variables 😄 

For instance, using Docker:

```
docker run --rm -p 3000:3000 gotenberg/gotenberg:7 \
       gotenberg \
       --my-property=foo
```

In a k8s environment, I guess it's related to https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/.

**Comment by thomastvedt** [comment]
Yeah, args was the first thing I tried, something like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appname }}
spec:
  replicas: {{  .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname}}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: {{ .Values.appname}}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          args:
            - "--api-disable-health-check-logging=true"
          securityContext:
            privileged: false
            runAsUser: 1001
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 3000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              port: 3000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 60
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 800m            
```

results in the pod failing to start with the following errormessage:

`[FATAL tini (6)] exec --api-disable-health-check-logging=true failed: No such file or directory`

Dockerfile:
https://github.com/gotenberg/gotenberg/blob/5cad5ca11a7902de2afbbb79c24fd5781a81b165/build/Dockerfile#L170

I guess I'm missing something 😅

**Comment by thomastvedt** [comment, marked as answer]
Finally got this working with:

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: htmltopdf   
          command: ['/usr/bin/tini', 'gotenberg', '--', '--api-disable-health-check-logging=true']
```

I'm not sure why it didn't work with args, but I'm happy now with less logging :) 

Thanks for feedback @gulien 👍
