### DISCUSSION TITLE
PDF Returning blank using laravel sail, but otherwise fine

### DISCUSSION THREAD

**Discussion by djsall** [gotenberg/gotenberg#600] [Q&A] [answered]
Hello!

I'm using Laravel sail, to host my Laravel application.
The gotenberg container works fine when using external URLs, like google.com, but if I use "http://localhost/invoice/1" (which displays "\<h1>Test\</h1>"), I get a blank PDF.

The command I use is: `curl --request POST 'http://localhost:3000/forms/chromium/convert/url' --form 'url="http://localhost/invoice/1/"' -o my.pdf`

If I use: `curl --request POST 'http://localhost:3000/forms/chromium/convert/url' --form 'url="https://google.com"' -o my.pdf` it works fine.

Docker compose:

```
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - gotenberg
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    gotenberg:
        image: gotenberg/gotenberg:7
        ports:
            - '3000:3000'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
```

Edit: for anyone else that experiences issues here, just use http://gotenberg:3000 instead of localhost.
