### DISCUSSION TITLE
Gotenberg - frequently high CPU usage in idle

### DISCUSSION THREAD

**Discussion by titro** [gotenberg/gotenberg#628] [Q&A] [answered]
Hi all,

the gotenberg docker container is causing a very high CPU usage on my RPI 4 frequently:
![image](https://user-images.githubusercontent.com/4005090/230980520-ef8277da-0205-4e85-9d33-c4d16f69bf08.png)

The other peak is the paperless training fom paperless-ngx. But the green one is from gotenberg and i have no idea why this container needs so many ressources over a long time, even in idle. As you can see (compared to the small paperless training peak) it is not starting at a certain time , e.g. once a hour or so

Running it on a RPI 4 with docker. The Compose:

```
version: "3.4"
services:
   gotenberg:
    image: gotenberg/gotenberg:7.8.2
    restart: unless-stopped
    ports:
      - 3000:3000
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=false"
      - "--chromium-allow-file-access-from-files=true"
      - "--chromium-allow-insecure-localhost=true"
      - "--chromium-allow-list=.*"
      - "--chromium-disable-web-security=true" 
      - "--api-timeout=400s"
   tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
    ports:
      - 9998:9998
```

Any hints?
