### DISCUSSION TITLE
Gotenberg issue - LibreOffice listener: context done: context deadline exceeded

### DISCUSSION THREAD

**Discussion by dreammirror000** [gotenberg/gotenberg#682] [Q&A]
Hello all,
I have been fighting with this since yesterday and all similar 2022 fixes didn't work for me (#442 and others around that time) . 
I have the following error when loading an office file : 

**paperless :** 
`documents.consumer.ConsumerError: test.docx: Error occurred while consuming document test.docx: Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'`
**gotenberg:**
`ERR ts=1694449413.5756998 logger=api msg=convert to PDF: lock long-running LibreOffice listener: start long-running LibreOffice listener: execute LibreOffice listener: context done: context deadline exceeded trace=8e203b16-539f-4ac8-9df7-6f90dc01bc97 remote_ip=192.168.80.6 host=gotenberg:3000 uri=/forms/libreoffice/convert method=POST path=/forms/libreoffice/convert referer= user_agent=python-httpx/0.24.1 status=503 latency=10213915928 latency_human=10.213915928s bytes_in=112574 bytes_out=19`

**Deployment on a Syno 220+:** 
```
version: "4.0"
services:
  redis:
    image: redis
    container_name: PaperlessNGX-REDIS
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperlessngx/redis:/data:rw

  db:
    image: postgres
    container_name: PaperlessNGX-DB
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperlessngx/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: XXXXXX
      POSTGRES_PASSWORD: XXXXXX

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: PaperlessNGX
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - gotenberg
      - tika
    ports:
      - 8777:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume1/docker/paperlessngx/data:/usr/src/paperless/data
      - /volume1/docker/paperlessngx/media:/usr/src/paperless/media
      - /volume1/docker/paperlessngx/export:/usr/src/paperless/export
      - /volume1/docker/paperlessngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: XXXXXXXX
      USERMAP_GID: XXXXXXXX
      PAPERLESS_URL: https://paperless.xxxxxxxx.synology.me
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperless.xxxxxxx.synology.me
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIME_ZONE: Europe/Paris
      PAPERLESS_ADMIN_USER: XXXXXX
      PAPERLESS_ADMIN_PASSWORD: XXXXXX
      PAPERLESS_OCR_LANGUAGE: fra+eng

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    container_name: gotenberg
    ports:
      - 3000:3000
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  
  tika:
    image: ghcr.io/paperless-ngx/tika
    container_name: tika
    ports:
      - 9998:9998
    restart: unless-stopped
```
