### DISCUSSION TITLE
Cors error

### DISCUSSION THREAD

**Discussion by mbohovic** [gotenberg/gotenberg#713] [Q&A]
I have gotenberg on localhost:9055 and I call it on localhost:6006
I have a CORS error, please how can I solve it?
I installed Gotenberg using docker compose

```
version: "3"
services: 
  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "9055:3000"
```

i tired
`docker run -e ALLOW_ORIGINS='http://localhost:6006'  --rm -p 9055:3000 gotenberg/gotenberg:7`
failed, not working

Please help, thanks
