### DISCUSSION TITLE
Testing locally against a non-dockerized app

### DISCUSSION THREAD

**Discussion by Morzaram** [gotenberg/gotenberg#886] [Q&A] [answered]
Hey there, I'm trying to test things locally on a non dockerized rails app. 
with my rails app running at `localhost:3000`

My docker compose is
```
version: '3'
services:
   gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--api-port=3001"
      - "--chromium-allow-insecure-localhost=true"
      - "--chromium-disable-web-security=true"
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

and I'm calling
```sh
curl \
--request POST http://localhost:3001/forms/chromium/convert/url \
--header 'Gotenberg-Trace: debug' \
--form url=http://localhost:3000/render-invoice-pdf \
--form 'waitForExpression=window.pdfStatus === '\''ready'\''' \
-o my.pdf
```
and also swapping the url with
```sh

curl \
--request POST http://localhost:3001/forms/chromium/convert/url \
--header 'Gotenberg-Trace: debug' \
--form url=http://host.docker.internal:3000/render-invoice-pdf \
--form 'waitForExpression=window.pdfStatus === '\''ready'\''' \
-o my.pdf
```

the only thing I'm getting from the console is

```
Attaching to gotenberg-1
gotenberg-1  |
gotenberg-1  |   _____     __           __
gotenberg-1  |  / ___/__  / /____ ___  / /  ___ _______ _
gotenberg-1  | / (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
gotenberg-1  | \___/\___/\__/\__/_//_/_.__/\__/_/  \_, /
gotenberg-1  |                                    /___/
gotenberg-1  |
gotenberg-1  | A Docker-powered stateless API for PDF files.
gotenberg-1  | Version: 8.5.1
gotenberg-1  | -------------------------------------------------------
gotenberg-1  | [SYSTEM] modules: api chromium exiftool libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook
gotenberg-1  | [SYSTEM] chromium: Chromium ready to start
gotenberg-1  | [SYSTEM] libreoffice-api: LibreOffice ready to start
gotenberg-1  | [SYSTEM] prometheus: collecting metrics
gotenberg-1  | [SYSTEM] pdfengines: exiftool libreoffice-pdfengine pdfcpu pdftk qpdf
gotenberg-1  | [SYSTEM] api: server listening on port 3001
gotenberg-1  | {"level":"error","ts":1716563305.0813122,"logger":"api","msg":"convert URL to PDF: convert to PDF: context deadline exceeded","trace":"debug","remote_ip":"192.168.65.1","host":"localhost:3001","uri":"/forms/chromium/convert/url","method":"POST","path":"/forms/chromium/convert/url","referer":"","user_agent":"curl/8.6.0","status":503,"latency":30006975472,"latency_human":"30.006975472s","bytes_in":341,"bytes_out":19}
```

but for some reason it's not pinging my rails server. Any ideas? I'm still relatively new to docker so apologies and thank in advance...
