### DISCUSSION TITLE
Need help (Laravel 10)

### DISCUSSION THREAD

**Discussion by aeq-dev** [gotenberg/gotenberg#889] [Q&A] [answered]
Hi,
I'm trying to print blade view using url, Stream 
Url : 
```
 $request = Gotenberg::chromium('http://gotenberg:3000')
                        ->pdf()
                        ->skipNetworkIdleEvent()
                        ->url(url('template4'));
```
I get a blank pdf page, while if I use other url like google.com, it works fine.
NB: I can access to `url('template4')`.

Stream : 
```
$inv = view('print.sales.templates.4.main')->render();

                    $request = Gotenberg::chromium('http://gotenberg:3000')
                        ->pdf()
                        ->html(Stream::string('my.html', $inv));
```
It works but without CSS !! (I'm using boostrap css)

What am I missing ?

**Comment by gulien** [comment]
Hello @aeq-dev 

> NB: I can access to url('template4').

But is  your Gotenberg container able to access it?

**Comment by aeq-dev** [comment]
Thanks @gulien for reply,
Yes it should coz it's a public url.
And after checking the debug console, I found this error : 
```

gotenberg_1   | {"level":"debug","ts":1716800006.8320892,"logger":"chromium.browser","msg":"start process"}
gotenberg_1   | {"level":"debug","ts":1716800006.9577649,"logger":"chromium.browser","msg":"[0527/085326.957561:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory\n"}
gotenberg_1   | {"level":"debug","ts":1716800006.9587862,"logger":"chromium.browser","msg":"[0527/085326.958711:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory\n"}
gotenberg_1   | {"level":"debug","ts":1716800006.958901,"logger":"chromium.browser","msg":"[0527/085326.958820:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory\n"}
```

Here's my docker compose : 

```
gotenberg:
    platform: linux/amd64
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-allow-insecure-localhost=true"
      - "--chromium-disable-web-security=true"
      - "--chromium-ignore-certificate-errors=true"
      - "--api-timeout=30s"
      - "--log-level=debug"
      - "--chromium-allow-file-access-from-files=true"
      - "--chromium-clear-cache=true"
      - "--chromium-clear-cookies=true"

    ports:
      - "3000:3000"
```
