### ISSUE TITLE
Duplicated requests when using weebhook

### ISSUE THREAD

**Issue by jojomak13** [gotenberg/gotenberg#1085]
I have recently started using the webhooks feature for `forms/chromium/convert/html`.

However, when I send multiple requests sequentially (e.g., **4** requests), each with a **unique** number in the header based on `gotenberg-trace`, I receive the correct number of webhooks (**4** in this case). The issue is that some webhooks are duplicated, sharing the same `gotenberg-trace` and **PDF** content.

![Screenshot 2024-12-22 at 8 54 50 PM](https://github.com/user-attachments/assets/780f933b-59e1-4f85-a072-2476ccd064e4)
![Screenshot 2024-12-22 at 8 55 00 PM](https://github.com/user-attachments/assets/c6238295-9acf-418d-85ce-cd369e8f7a26)

**Comment by gulien** [comment]
Hey @jojomak13 👋

Which version of Gotenberg are you using?

**Comment by jojomak13** [comment]
i use the docker version 8

```yaml
  pdf:
    image: gotenberg/gotenberg:8
    container_name: pdf
    ports:
      - 3000:3000
```
