### ISSUE TITLE
Docker images on ghcr.io

### ISSUE THREAD

**Issue by ondrejsika** [gotenberg/gotenberg#1136]
What about to publish docker images also to ghcr.io?

**Comment by gulien** [comment]
Hello @ondrejsika,

I don't want to increase the number of registries, but do you have a use case for ghrc.io instead of Docker hub?

**Comment by ondrejsika** [comment]
Docker Hub has very low limits for anonymous image pulls.

**Comment by gulien** [comment]
This would require some updates from the ci perspective but why not!

**Comment by zombiehoffa** [comment]
This  is killing me right now so would be extremely appreciated if you could add ghcr.io. It' s not a bad idea to maintain two repos for reliability in case docker hub goes down or github starts acting more like its parent company....

**Comment by caesay** [comment]
I echo the previous comments, for people with homelabs with many containers, dockerhub is basically unusable without paying for a pro subscription.

Since your builds are already in github actions, might be quite simple to add support for this.

Add this at the top of your workflow to give it permission to publish packages
```yaml
permissions:
  contents: read
  packages: write
```

Then add a login step somewhere, probably in your (already centralised) build-test-push action. 
```yml
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # provided automatically by github, no need to create
```

I think you'd then only need to add some extra tags to the bit that calls your `push.sh` script. e.g. 

```yml
    - name: Push
      if: inputs.docker_hub_username != ''
      shell: bash
      run: |
        .github/actions/build-test-push/push.sh \
          --tags "ghcr.io/${{ steps.build.outputs.tags }},${{ steps.build.outputs.tags }},${{ steps.build.outputs.tags_cloud_run }},${{ steps.build.outputs.tags_aws_lambda }}" \
          --dry-run "${{ inputs.dry_run }}"
```
