### ISSUE TITLE
8.17.2: log spamming `ERROR: unhandled page event *page.EventFrameStartedNavigating`

### ISSUE THREAD

**Issue by lindeberg** [gotenberg/gotenberg#1139]
Hi! Love Gotenberg. Thanks you so much!

From 8.17.2, this gets spammed in our logs every 10 seconds:  
`ERROR: unhandled page event *page.EventFrameStartedNavigating`

Downgrading to 8.17.1 makes it go away.

Not sure where it's from, it doesn't seem to have any noticable effect. But I hypothesize it's Prometheus scraping requests causing it. The prometheus scraping works fine though.

It's a Kubernetes set up like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotenberg.fullname" . }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "gotenberg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gotenberg.labels" . | nindent 8 }}
        {{- include "gotenberg.selectorLabels" . | nindent 8 }}
    {{- with .Values.deployment.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      # CKV_K8S_38: "Ensure that Service Account Tokens are only mounted where necessary"
      automountServiceAccountToken: false
      securityContext:
        # CKV_K8S_31: "Ensure that the seccomp profile is set to docker/default or runtime/default"
        seccompProfile:
          type: RuntimeDefault
      # Because 'enableServiceLinks' adds env var "API_PORT", which collides with the env var with same key used in Gotenberg.
      # https://kubernetes.io/docs/tutorials/services/connect-applications-service/#accessing-the-service
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "myrepo/gotenberg:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          securityContext:
            # https://github.com/gotenberg/gotenberg/blob/main/.env#L5
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            # https://github.com/gotenberg/gotenberg/issues/949
            # #checkov:skip=CKV_K8S_22: Unfortunately, readOnlyRootFilesystem is not supported in Gotenberg as of 8.17.1.
            readOnlyRootFilesystem: false
            # CKV_K8S_37: "Minimize the admission of containers with capabilities assigned"
            capabilities:
              drop:
                - all
          args:
          - gotenberg
          - --api-port=8443
          - --api-tls-cert-file=/var/run/autocert.step.sm/site.crt
          - --api-tls-key-file=/var/run/autocert.step.sm/site.key
          - --api-disable-download-from
          - --api-disable-health-check-logging
          - --chromium-allow-list=file:\/\/\/tmp\/.*\/index\.html
          - --chromium-auto-start
          - --chromium-disable-javascript
          - --prometheus-disable-route-logging
          - --pdfengines-disable-routes
          - --libreoffice-disable-routes
          - --webhook-disable
          env:
          - name: DISABLE_UNOCONV
            value: "true"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotenberg.fullname" . }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "gotenberg.selectorLabels" . | nindent 4 }}
```

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gotenberg.fullname" . }}
spec:
  endpoints:
    - port: https
      path: /prometheus/metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gotenberg.name" . }}
```
