### ISSUE TITLE
TLS certificate problem with time validity

### ISSUE THREAD

**Issue by lindeberg** [gotenberg/gotenberg#1173]
## Problem

intermittently (a.f.a.i.k), the TLS stops working, because certificates become interpreted as "NotTimeValid", even though the expiration date is far into the future. 

The error message from our requesting .NET-backend is: 
**"The remote certificate is invalid because of errors in the certificate chain: NotTimeValid"**

["NotTimeValid Specifies that the X509 chain is not valid due to an invalid time value, such as a value that indicates an expired certificate."](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainstatusflags?view=net-9.0)

## Context

- [Gotenberg 8.17.3](https://hub.docker.com/layers/gotenberg/gotenberg/8.17.3/images/sha256-73ee81b32abac22543b3d7d4d1b94c9f74ef4d8b6f727899ffb0960ecc0a0fae)
- Hosted on Kubernetes
- Certificates generated by Autocert
- No found correlation with Autocert cert renewal
- `date` in Gotenberg and the .NET-backend are correct
- Other .NET backends using the same Autocert to communicate works well
- Restarting the pods makes it work again (also triggers new cert generation)
- deployment.yaml:
    ```yaml
     ﻿ apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: {{ include "gotenberg.fullname" . }}
        labels:
          {{- include "gotenberg.labels" . | nindent 4 }}
      spec:
        revisionHistoryLimit: 0
        replicas: {{ .Values.replicaCount }}
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: {{ .Values.rollingUpdate.maxSurge }}
            maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
        selector:
          matchLabels:
            {{- include "gotenberg.selectorLabels" . | nindent 6 }}
        template:
          metadata:
            labels:
              {{- include "gotenberg.labels" . | nindent 8 }}
            annotations:
              {{- with .Values.deployment.annotations }}
              {{- toYaml . | nindent 8 }}
              {{- end }}
          spec:
            # CKV_K8S_38: "Ensure that Service Account Tokens are only mounted where necessary"
            automountServiceAccountToken: false
            securityContext:
              # CKV_K8S_31: "Ensure that the seccomp profile is set to docker/default or runtime/default"
              seccompProfile:
                type: RuntimeDefault
            # Because 'enableServiceLinks' adds env var "API_PORT", which collides with the env var with same key used in Gotenberg.
            # https://kubernetes.io/docs/tutorials/services/connect-applications-service/#accessing-the-service
            enableServiceLinks: false
            containers:
              - name: {{ .Chart.Name }}
                image: "mycompany.com/gotenberg:{{ .Chart.AppVersion }}"
                imagePullPolicy: Always
                volumeMounts:
                  - mountPath: /tmp
                    name: tmp-volume
                  - mountPath: /home/gotenberg
                    name: gotenberg-volume
                securityContext:
                  # https://github.com/gotenberg/gotenberg/blob/main/.env#L5
                  runAsUser: 1001
                  runAsGroup: 1001
                  runAsNonRoot: true
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  # CKV_K8S_37: "Minimize the admission of containers with capabilities assigned"
                  capabilities:
                    drop:
                      - all
                args:
                  - gotenberg
                  - --api-port=8443
                  - --api-tls-cert-file=/var/run/autocert.step.sm/site.crt
                  - --api-tls-key-file=/var/run/autocert.step.sm/site.key
                  - --api-disable-download-from
                  - --api-disable-health-check-logging
                  - --chromium-allow-list=file:\/\/\/tmp\/.*\/index\.html
                  - --chromium-auto-start
                  - --chromium-disable-javascript
                  - --chromium-restart-after=10 # "Clean-up memory by killing Chromium processes (memory usage grows over time with a long-running browser).":  https://github.com/gotenberg/gotenberg/discussions/1141#discussioncomment-12415528
                  - --prometheus-disable-route-logging
                  - --pdfengines-disable-routes
                  - --libreoffice-disable-routes
                  - --webhook-disable
                env:
                  - name: DISABLE_UNOCONV
                    value: "true"
                ports:
                  - name: https
                    containerPort: 8443
                    protocol: TCP
                livenessProbe:
                  httpGet:
                    path: /health
                    port: https
                    scheme: HTTPS
                readinessProbe:
                  httpGet:
                    path: /health
                    port: https
                    scheme: HTTPS
                resources:
                  {{- toYaml .Values.resources | nindent 12 }}
            volumes:
              - name: tmp-volume
                emptyDir:
                  sizeLimit: 100Mi
              - name: gotenberg-volume
                emptyDir:
                  sizeLimit: 100Mi
            terminationGracePeriodSeconds: 30
    ```
