### ISSUE TITLE
Request: Local install or CLI docker image?

### ISSUE THREAD

**Issue by Regenhardt** [gotenberg/gotenberg#310]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior

I'd like a way of using this in a pipeline without hosting it somewhere else. So in the pipeline I'd pull an image and just go `gotenberg readme.md -o readme.pdf` (for example) and have my markdown file printed to a pdf file.

## Current Behavior

Currently, I'd have to host this somewhere and then call that from the pipeline.

## Possible Solution

No idea how it's built inside or how go even works, but I suppose you could add something letting it be compiled to an executable.

## Context

There are a few current markdown-to-pdf cli tools, but none of those correctly convert every part of a markdown file to pdf (one example being <sup> tags in a heading).

## Your Environment

Gitlab Pipelines

**Comment by gulien** [comment]
Hello @Regenhardt 

It's not possible to have a single binary as Gotenberg relies heavily on dependencies like Google Chrome.

I guess you could start the Docker image in you job and then call the `localhost` URL in order to convert your document.

```yaml
your_job:
  image: your_base_image
  services:
    - name: gotenberg:6
  variables:
    //TODO
  script:
    - curl --request POST --url http://localhost:3000/convert/markdown --header 'Content-Type: multipart/form-data' --form files=@index.html --form files=@README.md  -o README.pdf
```

I guess it also depends on how you have configured your GitLab CI.
