### ISSUE TITLE
Chromium failed to start in 7.0.2

### ISSUE THREAD

**Issue by mkotsalainen** [gotenberg/gotenberg#327]
* Gutenberg version: 7.0.2
* docker-compose version 1.29.1, build c34c88b2
* docker version 20.10.6, build 370c289 

This project works locally but when I try to run this on a t3a.medium AWS instance running Docker I get this error:

2021-08-25T17:09:04 - {"level":"error","ts":1629907744.42355,"logger":"api","msg":"handle request: convert HTML to PDF: convert to PDF: chromium PDF: chrome failed to start:\n","trace":"9fec0f04-09a4-4785-ab8c-3337652a519b","remote_ip":"172.20.0.3","host":"gotenberg:7777","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"python-httpx/0.14.3","status":500,"latency":10003991770,"latency_human":"10.00399177s","bytes_in":361,"bytes_out":21}

I tried increasing mem limits in dc file like so but it doesn't seem to work. Any tips on how to debug this?

```
 gotenberg:
    image: gotenberg/gotenberg:7
    command: gotenberg --api-port=7777 --api-process-timeout=10s --libreoffice-disable-routes --log-level=debug
    ports:
      - 7777:7777
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M

```
