### ISSUE TITLE
Button to deploy to heroku

### ISSUE THREAD

**Issue by Ajju2211** [gotenberg/gotenberg#383]
I want to deploy it to heroku.
But I don't know how to run the docker container on heorku.
Can you please provide the heroku deploy to heroku directly which will help me to complete my project.

**Comment by f16z** [comment]
I was able to get this deployed to heroku using their Dockerfile deployment method:
https://devcenter.heroku.com/articles/build-docker-images-heroku-yml

`Dockerfile`
```
FROM gotenberg/gotenberg:7
CMD ["gotenberg"]
```

`hereoku.yml`
```
build:
  docker:
    web: Dockerfile

run:
  web: gotenberg --api-port-from-env PORT
```

**Comment by AhmedBHameed** [comment]
For those who want to deploy Gotenberg to heroku via Terraform, here is a working script


```tf
resource "heroku_app" "gotenberg_pdf_generator" {
  name   = "gotenberg-pdf-generator"
  region = "eu"
  stack = "container"

  config_vars = {
    # Recommended: Secure your instance
    GOTENBERG_API_BASIC_AUTH_USERNAME = var.gotenberg_auth_username
    GOTENBERG_API_BASIC_AUTH_PASSWORD = var.gotenberg_auth_key
  }

  organization {
    name = var.heroku_organization
  }
}


resource "heroku_build" "gotenberg_pdf_generator_build" {
  app_id = heroku_app.gotenberg_pdf_generator.id

  source {
    # The path must be a subdirectory of your Terraform project
    path = "apps/gotenberg" 
  }
}

resource "heroku_formation" "gotenberg_formation" {
  app_id   = heroku_app.gotenberg_pdf_generator.id
  type       = "web"
  quantity   = 1
  size       = "Standard-1x"

  # Ensure the app doesn't try to start until the build is finished
  depends_on = [heroku_build.gotenberg_pdf_generator_build]
}
```

Inside `apps/gotenberg`, there are 2 files

`apps/gotenberg/Dockerfile`
```
FROM gotenberg/gotenberg:latest

CMD ["gotenberg"]
```


and `apps/gotenberg/heroku.yml`
```yml
build:
  docker:
    web: Dockerfile

run:
  web: gotenberg --api-enable-basic-auth  --api-port-from-env PORT
```
