### ISSUE TITLE
stable operation under load

### ISSUE THREAD

**Issue by KraMorK** [gotenberg/gotenberg#537]
I started the application in kubernetes
with this manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-convert-service-gotenberg-deployment
  labels:
    name: file-convert-service-gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
        - name: gotenberg
          securityContext:
            privileged: false
            runAsUser: 1001
          image: "dreg.example.com/dockerhub/gotenberg/gotenberg:7.7.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: health
              port: http
          readinessProbe:
            httpGet:
              path: health
              port: http
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
```
if the application is idle for a couple of minutes, then the first conversion attempts will be unsuccessful, a 500 error will be thrown, and such an entry in the logs:
```
{"level":"error","ts":1667816697.079552,"logger":"api","msg":"convert to PDF: unoconv PDF: unix process error: wait for unix process: exit status 5","trace":"cff58268-fc06-412b-b76c-9c67e3941c78","remote_ip":"10.99.145.2","host":"file-convert-service/example.com","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"curl/7.79.1","status":500,"latency":446446326,"latency_human":"446.446326ms","bytes_in":100566,"bytes_out":21}
```
after that, I keep trying, every second after an unsuccessful response, and the code 500 is returned to me 7-8 more times. after that the conversion is successful. how can i fix this? maybe I should disable unnecessary modules? or something else to tweak?

**Comment by KraMorK** [comment]
added an argument, but it did not fix the situation:(
```
          command: ["gotenberg"]
          args: ["--uno-listener-restart-threshold=0"]
```

**Comment by gulien** [comment]
Hello @KraMorK,

I wonder if increasing the CPU and/or the memory limit may resolve your issue.

**Comment by KraMorK** [comment]
Hello @gulien,
increased resources
```
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 1024Mi
```
The situation has not changed
Application does not consume allocated resources,
actual consumption no more than 300 mCPU and 300 Mb RAM
