### ISSUE TITLE
Paperless NGX - Import Office Dokumente - Error while converting document to PDF: 503 Server Error

### ISSUE THREAD

**Issue by mdangst** [gotenberg/gotenberg#607]
In Paperless NGX the import of MS Office documents (.docx etc.) fails. It does not work with any gotenberg version as contained in the list below.

![503 Server Error](https://user-images.githubusercontent.com/118683900/221420170-44ad7843-d096-4eed-be2c-2f74d570dd78.PNG)
7
7.4
7.6
7.7.2

**Comment by gulien** [comment]
Hello @mdangst

Increase the timeout and you should be fine!

**Comment by mdangst** [comment]
Hi
Also with the increased timeout it does not work, see the error below.
![image](https://user-images.githubusercontent.com/118683900/221424699-9a2a2f52-9e9a-45d4-9b8a-d44455e81a0d.png)

Below you may find my setup in portainer:
#....
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/forms/libreoffice/convert#
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
#...
  gotenberg:
    container_name: paperless-gotenberg
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    environment:
      CHROMIUM_DISABLE_ROUTES: 1
    command:
      - 'gotenberg'
      - '--chromium-disable-javascript=true'
      - '--chromium-allow-list=file:///tmp/.*'
      - '--api-timeout=60'      
    networks:
      - internal

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: tika
    ports:
      - 9998:9998
    restart: always
    networks:
      - internal
#...

**Comment by gulien** [comment]
Your setup is somewhat wrong. Please try:


```yaml
gotenberg:
  container_name: paperless-gotenberg
  image: gotenberg/gotenberg:7
  restart: unless-stopped
  command:
    - 'gotenberg'
    - '--chromium-disable-routes=true'
    - '--api-timeout=60s'
  networks:
    - internal
```
