### ISSUE TITLE
perfomance running on eks

### ISSUE THREAD

**Issue by avifreege** [gotenberg/gotenberg#609]
running gotenberg on eks with the following args:
```
  extraArgs:
    api-timeout: "1m"
    api-disable-health-check-logging: "" 
```
with the following resources:

```
  resources:
    limits:
      cpu: 1600m
      memory: 3000Mi
    requests:
      cpu: 1100m
      memory: 1500Mi 
```
      
with hpa configuration of min 5 pods with cpu threshold of 50%
we are facing 20%-30%  (around 50 conversion per minute) error ratio with conversion returning 503, mainly on reaching the time outs of 1m  on file of 5mb and even 66kb.
Any missing configuration? or put more reousrces on goetnberg deployment?

gotenberg 7.7.2
