### ISSUE TITLE
Readiness endpoint

### ISSUE THREAD

**Issue by kevin-lindsay-1** [gotenberg/gotenberg#648]
In kubernetes, readiness is not the same as health; health refers to whether or not the pod is "still alive", readiness refers to whether or not the pod should be routed to.

For load balancing purposes, it would be very beneficial to have a separate "ready" endpoint from "health" endpoint; the service should only be considered unhealthy when it is unable to respond for long periods of time, and otherwise it should be unready until it becomes ready.

Health checks are typically long-polling, long timeout, with multiple retries that "reset" health state after 1 success, and are considered unhealthy after 12 or so, once every 10 seconds.

Readiness checks are typically short-polling, short timeout, where failures remove the pod from the service endpoints list, and successes add (if not exists) the pod to the service endpoints list.

From an implementation standpoint, health and readiness can be the same logic, but it's typically preferable to have them be separate so that a pod can state when it can't handle more requests, so as to not cause the health endpoint to fail unnecessarily.

For example, if readiness fails, the pod won't get new requests, and will be less likely to become so busy it can't respond to health checks.

Health checks, on the other hand, should generally immediately return a 200 unless something is definitely broken and would require a restart.

```yaml
// after 2 minutes of no responses from the health endpoint, consider this pod unhealthy, and restart it
// if the pod succeeds 1 health check, it is not unhealthy but busy; reset the counter
livenessProbe: 
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 12
  successThreshold: 1

// after 1 second of no responses from the readiness endpoint, consider this pod busy, and remove it from load balancing until it succeeds again
readinessProbe: 
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 1
  periodSeconds: 1
  timeoutSeconds: 1
  failureThreshold: 1
  successThreshold: 1
```
