### ISSUE TITLE
Inconsistent Gotenberg Docker Start Failures in PaperlessNGX Setup due to LibreOffice Failure

### ISSUE THREAD

**Issue by togut** [gotenberg/gotenberg#764]
Hi everyone,

I'm experiencing an issue with my Gotenberg instance within my PaperlessNGX Configuration. My Gotenberg Docker container fails to start quite often, although the occurrences are inconsistent. The logs (see below) indicate that the failure occurs at the LibreOffice module, after which the Docker container automatically restarts.

I have tried the following troubleshooting steps:

- Increasing the "libreoffice-start-timeout"
  > Result: The issue persists, just with a longer waiting time.

- Checking system resources and stopping all other containers outside of the PaperlessNGX Configuration
  > Result: There's enough RAM and processor capacity available (at least 512 MB). No change in conditions, as the issue eventually resolves.

- Checking Docker and system logs
  > Result: No significant log entries found.

Does anyone have any insights on the root cause of these failed startup attempts, or suggestions on how to resolve this issue?

Thank you!

**My System:**
```
Model: Synology DS918+
CPU: Intel Celeron J3455 Quad-Core, 1.5 GHz (base)
RAM: 4 GB DDR3L
DSM Version: DSM 7.2.1-69057 Update 3
```

**My `docker-compose.yml`:**
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    user: "1047:100"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/PaperlessNGX/redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - /volume1/PaperlessNGX/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ***

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume1/PaperlessNGX/data:/usr/src/paperless/data
      - /volume1/PaperlessNGX/media:/usr/src/paperless/media
      - /volume1/PaperlessNGX/export:/usr/src/paperless/export
      - /volume1/PaperlessNGX/input:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_URL: "https://***"   
      PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'

  gotenberg:
    image: docker.io/gotenberg/gotenberg:latest
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--api-timeout=400s"
      - "--libreoffice-auto-start=true"
      - "--libreoffice-start-timeout=30s"
      - "--log-level=debug"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
```
> Note: "***" marks censored data.

**Log from the failed and finally succeeded startup:**
```
  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 7.10.2
-------------------------------------------------------
[SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] chromium: Chromium ready to start
[SYSTEM] pdfengines: libreoffice-pdfengine pdfcpu pdftk qpdf
[SYSTEM] prometheus: collecting metrics
{"level":"debug","ts":1704182764.1200373,"logger":"libreoffice-api.libreoffice","msg":"start process"}
{"level":"debug","ts":1704182764.1206288,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/5f174ced-d0f5-47b7-a715-41ebe26aed0d/0490b868-7ee6-492d-a638-0f7d64999766 --accept=socket,host=127.0.0.1,port=36355,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
{"level":"debug","ts":1704182794.120505,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"unix process killed"}
[FATAL] starting api: waiting for modules readiness: context done while waiting for LibreOffice to be ready: context deadline exceeded

  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 7.10.2
-------------------------------------------------------
[SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] chromium: Chromium ready to start
{"level":"debug","ts":1704182810.872834,"logger":"libreoffice-api.libreoffice","msg":"start process"}
{"level":"debug","ts":1704182810.873976,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/cfe4e836-7267-48da-a730-4eb6b21cea96/e15a2a17-9ee8-4f40-9f32-b96e9f780eb3 --accept=socket,host=127.0.0.1,port=40582,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
[SYSTEM] prometheus: collecting metrics
[SYSTEM] pdfengines: libreoffice-pdfengine pdfcpu pdftk qpdf
{"level":"debug","ts":1704182811.706562,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"unix process already killed"}
{"level":"debug","ts":1704182811.7066658,"logger":"libreoffice-api.libreoffice","msg":"got exit code 81, e.g., LibreOffice first start"}
{"level":"debug","ts":1704182811.7067406,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/cfe4e836-7267-48da-a730-4eb6b21cea96/e15a2a17-9ee8-4f40-9f32-b96e9f780eb3 --accept=socket,host=127.0.0.1,port=40582,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
{"level":"debug","ts":1704182811.7072499,"logger":"libreoffice-api.libreoffice","msg":"waiting for the LibreOffice socket to be available..."}
{"level":"debug","ts":1704182840.8739831,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"unix process killed"}
[FATAL] starting api: waiting for modules readiness: context done while waiting for LibreOffice to be ready: context deadline exceeded

  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 7.10.2
-------------------------------------------------------
[SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
{"level":"debug","ts":1704182853.3903372,"logger":"libreoffice-api.libreoffice","msg":"start process"}
{"level":"debug","ts":1704182853.3908494,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/7a56dc1c-3688-4178-82f7-013aedb39010/1c6c6a36-a840-4326-89fc-71148fcc1577 --accept=socket,host=127.0.0.1,port=37556,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
[SYSTEM] chromium: Chromium ready to start
[SYSTEM] pdfengines: libreoffice-pdfengine pdfcpu pdftk qpdf
[SYSTEM] prometheus: collecting metrics
{"level":"debug","ts":1704182856.3327465,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"unix process already killed"}
{"level":"debug","ts":1704182856.332798,"logger":"libreoffice-api.libreoffice","msg":"got exit code 81, e.g., LibreOffice first start"}
{"level":"debug","ts":1704182856.333757,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/7a56dc1c-3688-4178-82f7-013aedb39010/1c6c6a36-a840-4326-89fc-71148fcc1577 --accept=socket,host=127.0.0.1,port=37556,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
{"level":"debug","ts":1704182856.334077,"logger":"libreoffice-api.libreoffice","msg":"waiting for the LibreOffice socket to be available..."}
[FATAL] starting api: waiting for modules readiness: context done while waiting for LibreOffice to be ready: context deadline exceeded

  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 7.10.2
-------------------------------------------------------
[SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
{"level":"debug","ts":1704182898.8556669,"logger":"libreoffice-api.libreoffice","msg":"start process"}
{"level":"debug","ts":1704182898.8564615,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/4a4bb4e7-0e9a-452a-ace9-9495ce9d36fe/600b0fce-f71f-40b4-bb45-da479a21b857 --accept=socket,host=127.0.0.1,port=33810,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
[SYSTEM] chromium: Chromium ready to start
[SYSTEM] prometheus: collecting metrics
[SYSTEM] pdfengines: libreoffice-pdfengine pdfcpu pdftk qpdf
{"level":"debug","ts":1704182899.5488813,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"unix process already killed"}
{"level":"debug","ts":1704182899.548947,"logger":"libreoffice-api.libreoffice","msg":"got exit code 81, e.g., LibreOffice first start"}
{"level":"debug","ts":1704182899.5490274,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/4a4bb4e7-0e9a-452a-ace9-9495ce9d36fe/600b0fce-f71f-40b4-bb45-da479a21b857 --accept=socket,host=127.0.0.1,port=33810,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
{"level":"debug","ts":1704182899.549376,"logger":"libreoffice-api.libreoffice","msg":"waiting for the LibreOffice socket to be available..."}
[FATAL] starting api: waiting for modules readiness: context done while waiting for LibreOffice to be ready: context deadline exceeded
{"level":"debug","ts":1704182928.8607218,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"unix process killed"}

  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 7.10.2
-------------------------------------------------------
[SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] chromium: Chromium ready to start
[SYSTEM] pdfengines: libreoffice-pdfengine pdfcpu pdftk qpdf
[SYSTEM] prometheus: collecting metrics
{"level":"debug","ts":1704182941.2924042,"logger":"libreoffice-api.libreoffice","msg":"start process"}
{"level":"debug","ts":1704182941.2929616,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/dbb9d334-a5db-4fb1-a375-839036d870d4/eec2cd24-b6a9-487a-9033-862f9e3f54fb --accept=socket,host=127.0.0.1,port=42034,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
{"level":"debug","ts":1704182942.9613705,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"unix process already killed"}
{"level":"debug","ts":1704182942.961427,"logger":"libreoffice-api.libreoffice","msg":"got exit code 81, e.g., LibreOffice first start"}
{"level":"debug","ts":1704182942.9614975,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/dbb9d334-a5db-4fb1-a375-839036d870d4/eec2cd24-b6a9-487a-9033-862f9e3f54fb --accept=socket,host=127.0.0.1,port=42034,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
{"level":"debug","ts":1704182942.9621396,"logger":"libreoffice-api.libreoffice","msg":"waiting for the LibreOffice socket to be available..."}
[FATAL] starting api: waiting for modules readiness: context done while waiting for LibreOffice to be ready: context deadline exceeded

  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 7.10.2
-------------------------------------------------------
[SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] chromium: Chromium ready to start
[SYSTEM] prometheus: collecting metrics
[SYSTEM] pdfengines: libreoffice-pdfengine pdfcpu pdftk qpdf
{"level":"debug","ts":1704182982.6526222,"logger":"libreoffice-api.libreoffice","msg":"start process"}
{"level":"debug","ts":1704182982.6531773,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/80bff166-1413-4112-a095-8edf79c6ab9d/793f6792-7449-4419-a3f3-b6aadcb42e5d --accept=socket,host=127.0.0.1,port=34011,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
{"level":"debug","ts":1704182983.8925269,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"unix process already killed"}
{"level":"debug","ts":1704182983.8926158,"logger":"libreoffice-api.libreoffice","msg":"got exit code 81, e.g., LibreOffice first start"}
{"level":"debug","ts":1704182983.8926933,"logger":"libreoffice-api.libreoffice.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/80bff166-1413-4112-a095-8edf79c6ab9d/793f6792-7449-4419-a3f3-b6aadcb42e5d --accept=socket,host=127.0.0.1,port=34011,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
{"level":"debug","ts":1704182983.8930619,"logger":"libreoffice-api.libreoffice","msg":"waiting for the LibreOffice socket to be available..."}
[SYSTEM] libreoffice-api: LibreOffice automatically started
{"level":"debug","ts":1704182985.5484512,"logger":"libreoffice-api.libreoffice","msg":"LibreOffice socket available"}
{"level":"debug","ts":1704182985.5485227,"logger":"libreoffice-api.libreoffice","msg":"process successfully started"}
[SYSTEM] api: server listening on port 3000
```
