### ISSUE TITLE
PDF version 1.5 is support?

### ISSUE THREAD

**Issue by CharlesLee1120** [gotenberg/gotenberg#774]
```
...
      containers:
        - name: app
          image: 'thecodingmachine/gotenberg:7'
          args:
            - gotenberg
            - '--api-read-timeout'
            - 600s
            - '--api-process-timeout'
            - 600s
            - '--api-write-timeout'
            - 600s
          ports:
            - name: http-3000
              containerPort: 3000
              protocol: TCP
...
```

I use docker to run gotenberg, successfully created a PDF file, PDF version is 1.4, if you want to create PDF version 1.5, now support? 
Thanks to the developers.
