### ISSUE TITLE
context deadline exceeded with default configuration

### ISSUE THREAD

**Issue by jaime-pineiro-imatia** [gotenberg/gotenberg#863]
I started gotenberg in docker compose with this configuration:
```
 gotenberg-8-4:
    image: gotenberg/gotenberg:8.4
    container_name: gotenberg-8-4
    restart: unless-stopped
    command: gotenberg --log-level=info
    tty: true
    networks:
      - firmaOverlay
```
Then i throw a test battery with 50 request in 10 simultaneous threads. I always get an error for the first request like this:

`2024/04/24 14:26:40.519 ERROR   api     convert to PDF: process first start: start process: LibreOffice socket not available: context deadline exceeded {"trace": "d6f09a60-b2f0-43ba-83a8-c66e736232d8", "remote_ip": "172.20.0.5", "host": "gotenberg:3000", "uri": "/forms/libreoffice/convert", "method": "POST", "path": "/forms/libreoffice/convert", "referer": "", "user_agent": "Apache-HttpClient/4.5.10 (Java/11.0.20.1)", "status": 503, "latency": 20021365109, "latency_human": "20.021365109s", "bytes_in": 1026963, "bytes_out": 19}
`

And some errors apparently randomly like this:

`2024/04/24 14:27:31.585 ERROR   api     convert to PDF: context deadline exceeded       {"trace": "99f7e24f-2152-4ba7-9826-0db93e389dee", "remote_ip": "172.20.0.5", "host": "gotenberg:3000", "uri": "/forms/libreoffice/convert", "method": "POST", "path": "/forms/libreoffice/convert", "referer": "", "user_agent": "Apache-HttpClient/4.5.10 (Java/11.0.20.1)", "status": 503, "latency": 30001716301, "latency_human": "30.001716301s", "bytes_in": 1026973, "bytes_out": 19}`

After reviewing issue [https://github.com/gotenberg/gotenberg/issues/763](https://github.com/gotenberg/gotenberg/issues/763) i tried by adding the configuration values " --libreoffice-auto-start=true" and "--libreoffice-restart-after=0", with this configuration every 50 requests are processed succesfully. my question is, shouldn't default values for these properties be changed?
