### ISSUE TITLE
Header date variable always shows UTC timezone

### ISSUE THREAD

**Issue by luizjunior05** [gotenberg/gotenberg#887]
Is there any way to set the time zone and language?

Would it be feasible to set this in an environment variable?

- docker compose:
```
gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    restart: always
    environment:
      TZ: America/Sao_Paulo
```

- excerpt from the header.html:
```
<body>
  <div class="containerHeader">
    <div class="cleft">{{.Date}}</div>
    <div class="ccenter">{{.Title}}</div>
  </div>
</body>
```
