### ISSUE TITLE
Read-only filesystem and Chromium in v. 8.9.2

### ISSUE THREAD

**Issue by spewu** [gotenberg/gotenberg#949]
We just tried to upgrade from 8.9.1 to 8.9.2, and I see this error in the logs now:

```
  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 8.9.2
-------------------------------------------------------
[SYSTEM] modules: api chromium exiftool libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] libreoffice-api: LibreOffice ready to start
[SYSTEM] prometheus: collecting metrics
[SYSTEM] pdfengines: exiftool libreoffice-pdfengine pdfcpu pdftk qpdf
[FATAL] starting chromium: launch supervisor: start process: run exec allocator: chrome failed to start:
mkdir: cannot create directory '/home/gotenberg/.local': Read-only file system
touch: cannot touch '/home/gotenberg/.local/share/applications/mimeapps.list': No such file or directory
chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[11:11:0903/115241.735456:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
2024-09-03T11:52:41.737219989Z
```

It works fine if I downgrade to 8.9.1.

So, we need to disable running with a read-only file-system to continue with Gotenberg now? 😅

**Comment by gulien** [comment]
Hey @spewu 👋  thanks for the heads up!

@giamma is that what you were talking about?

**Comment by gulien** [comment]
@spewu I'm unable to reproduce this issue, but, on `arm64`, Chromium writes the same folders in the `/home/gotenberg` directory in version `8.9.1` and `8.9.2` 🤔 

Which platform are you using? `amd64`?

**Comment by spewu** [comment]
@gulien Thanks a lot for looking at this 🤩

We are running on Azure Kubernetes Service (AKS), and yes, we run on Linux amd64 (Ubuntu 22.04.4 LTS).

We wrap your image in our own, so that we can add our fonts:

```
FROM gotenberg/gotenberg:8.9.1

USER root

COPY fonts/* /usr/local/share/fonts/

USER gotenberg
```

And then we run it like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: likvido-gotenberg
  labels:
    app.kubernetes.io/name: likvido-gotenberg
    app.kubernetes.io/part-of: pdf
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: likvido-gotenberg
      app.kubernetes.io/part-of: pdf
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: likvido-gotenberg
        app.kubernetes.io/part-of: pdf
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: likvido-gotenberg
          image: "image-name"
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1500m
              memory: 1500Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsUser: 1001
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          command: ["gotenberg"]
          args: ["--api-timeout", "120s", "--chromium-auto-start", "true", "--chromium-restart-after", "10"]
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1
      volumes:
        - name: tmp
          emptyDir: {}
```

I expect that the reason we get the problem is because we set `readOnlyRootFilesystem: true` (but I have not tried running the image where I set this to false ... would you like me to test that?)

**Comment by gulien** [comment]
> I expect that the reason we get the problem is because we set readOnlyRootFilesystem: true (but I have not tried running the image where I set this to false ... would you like me to test that?)

That might be the issue 🤔 if you can try without read only that would be great! 

>  Mounts the container's root filesystem as read-only.

I'm not familiar with this, but I guess it allows writting on the `/tmp` folder?

**Comment by giamma** [comment]
@gulien  the fact I was referring to in the discussion is that I am aware of a commercial product for Windows that provides optional HTML->PDF conversion by means of Chrome, and which requires the user to install the "current version" of Chrome for HTML->PDF to work. 

A friend of mine who licensed that product for usage in his own software solution is now having issues in production since Chrome auto-updated to the latest version, because HTML->PDF conversion randomly gets stuck in Chrome, or between the commercial product and Chrome. 

This is why I wondered whether there was a risk that the Chrome that ships with Gotenberg could auto-update.

**Comment by gulien** [comment]
FYI @MaikuMori ^^

**Comment by panos--** [comment]
For me, mounting an `emptyDir` volume on `/home/gotenberg` works with `readOnlyRootFilesystem: true`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotenberg
  name: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      automountServiceAccountToken: false
      containers:
      - image: gotenberg/gotenberg:8.20.1@sha256:755f42d3331d434989234ef604e846edf5f473b22546d9fd9d3c974f6a26dc5e
        name: gotenberg
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        readinessProbe:
          httpGet:
            port: http
            path: /health
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            port: http
            path: /health
          initialDelaySeconds: 30
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: home
          mountPath: /home/gotenberg
      securityContext:
        fsGroup: 1001
      volumes:
      - name: tmp
        emptyDir: {}
      - name: home
        emptyDir: {}
```
